AWSアクセスチェックをAmplifyデプロイステータスのチェックに変更

diff --git a/.github/workflows/aws-access-check.yml b/.github/workflows/aws-access-check.yml
--- a/.github/workflows/aws-access-check.yml
+++ b/.github/workflows/aws-access-check.yml
@@ -1,16 +1,27 @@
-name: AWS access check
+name: Check Amplify Deploy status
 
 on:
   push:
+  pull_request_review:
+    types: [submitted]
   workflow_dispatch:
 
 env:
   AWS_REGION: ap-northeast-1 # set this to your preferred AWS region, e.g. us-west-1
+
 jobs:
-  deploy:
-    name: Deploy
+  run-amplify-deploy-check:
+    if: github.event.review.state == 'APPROVED'
     runs-on: ubuntu-latest
-    environment: production
+    steps:
+      - name: integration
+        run: |
+          echo "Integration"
+  dev_deployment:
+    runs-on: ubuntu-latest
+    if: contains(github.ref_name, 'feature') || contains(github.ref_name, 'backend')
+    environment: development # Environment の名前を指定
+    needs: integration
     # These permissions are needed to interact with GitHub's OIDC Token endpoint.
     permissions:
       id-token: write
@@ -32,7 +43,68 @@ jobs:
           echo "status=${status}"
           # echo "status=$status" >> $GITHUB_ENV
           if [ ${status} = "FAILED" ]; then
-            echo "Amplify deploy failed -branch ${branch}"
+            echo "Amplify deploy failed -branch:${branch}"
+            exit 1
+          fi
+        shell: bash
+
+  stg_deployment:
+    runs-on: ubuntu-latest
+    if: github.ref_name == 'staging'
+    environment: staging # Environment の名前を指定
+    needs: integration
+    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
+    permissions:
+      id-token: write
+      contents: read
+    steps:
+      - name: Configure AWS credentials from IAM Role
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Run AWS Amplify List Jobs
+        id: amplify
+        run: |
+          echo "Staging Env"
+          # branch=${{github.event.pull_request.head.ref}}
+          branch="main"
+          status=$(aws amplify list-jobs --app-id ${{secrets.AMPLIFY_APP_ID}} --branch-name ${branch} --query jobSummaries[0].status | tr -d '"')
+          echo "status=${status}"
+          # echo "status=$status" >> $GITHUB_ENV
+          if [ ${status} = "FAILED" ]; then
+            echo "Amplify deploy failed -branch:${branch}"
+            exit 1
+          fi
+        shell: bash
+  prod_deployment:
+    runs-on: ubuntu-latest
+    if: github.ref_name == 'main'
+    environment: production # Environment の名前を指定
+    needs: integration
+    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
+    permissions:
+      id-token: write
+      contents: read
+    steps:
+      - name: Configure AWS credentials from IAM Role
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Run AWS Amplify List Jobs
+        id: amplify
+        run: |
+          echo "Production Env"
+          # branch=${{github.event.pull_request.head.ref}}
+          branch="main"
+          status=$(aws amplify list-jobs --app-id ${{secrets.AMPLIFY_APP_ID}} --branch-name ${branch} --query jobSummaries[0].status | tr -d '"')
+          echo "status=${status}"
+          # echo "status=$status" >> $GITHUB_ENV
+          if [ ${status} = "FAILED" ]; then
+            echo "Amplify deploy failed -branch:${branch}"
             exit 1
           fi
         shell: bash
