Fix AWS access check script to handle errors

diff --git a/.github/workflows/aws-access-check.yml b/.github/workflows/aws-access-check.yml
--- a/.github/workflows/aws-access-check.yml
+++ b/.github/workflows/aws-access-check.yml
@@ -28,7 +28,11 @@ jobs:
           echo "Development Deployment"
           # branch=${{github.event.pull_request.head.ref}}
           branch="main"
-          status=$(aws amplify list-jobs --app-id ${{secrets.AMPLIFY_APP_ID}} --branch-name $branch --query jobSummaries[0].status)
+          status=$(aws amplify list-jobs --app-id ${{secrets.AMPLIFY_APP_ID}} --branch-name ${{branch}} --query jobSummaries[0].status)
+          if [ $? -ne 0 ]; then
+            echo "Failed to list jobs ${{ branch }}"
+            exit 1
+          fi
           echo "status=$status"
           echo "status=$status" >> $GITHUB_ENV
         shell: bash
